bioquery/articles/urls.py
from django.urls import path

from .views import (
    new,
    detail,
    references,
    new_reference,
    delete_reference,
    dnas,
    new_dna,
    edit_dna,
    delete_dna,
    delete_article,
    update_article,
    edit_reference,
)


app_name = "articles"

urlpatterns = [
    path("", new, name="new"),
    path("dnas/", dnas, name="dnas"),
    path("dnas/new/", new_dna, name="new_dna"),
    path("dnas/<int:id>/edit/", edit_dna, name="edit_dna"),
    path("references/", references, name="references"),
    path("references/new/", new_reference, name="new_reference"),
    path("references/<int:id>/delete/", delete_reference, name="delete_reference"),
    path("references/<int:id>/edit/", edit_reference, name="edit_reference"),
    path("dnas/<int:id>/delete/", delete_dna, name="delete_dnas"),
    path("<str:slug>/", detail, name="detail"),
    path("<str:slug>/delete/", delete_article, name="delete_article"),
    path("<str:slug>/edit/", update_article, name="edit_article"),
]

bioquery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


admin.site.enable_nav_sidebar = False

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("bioquery.articles.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("bioquery.core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bioquery/core/models.py
from django.db import models
from django.utils import timezone

from .managers import CategoryDB, DNADB, PhotoDB, ReferenceDB, CommentDB


class Category(models.Model):
    name = models.CharField("nome", max_length=255)
    description = models.TextField("descrição")

    objects_db = CategoryDB

    class Meta:
        verbose_name_plural = "categorias"
        verbose_name = "categoria"
        ordering = ("name",)

    def __str__(self):
        return self.name


class DNA(models.Model):
    name = models.CharField("nome", max_length=255)
    sequence = models.TextField("sequência")
    user = models.ForeignKey("auth.User", verbose_name="usuário", on_delete=models.CASCADE)

    objects_db = DNADB

    class Meta:
        verbose_name_plural = "DNA's"
        verbose_name = "DNA"
        ordering = ("-name",)

    def __str__(self):
        return self.name


class Photo(models.Model):
    user = models.ForeignKey("auth.User", verbose_name="usuário", on_delete=models.CASCADE)
    file = models.FileField("arquivo")

    objects_db = PhotoDB

    class Meta:
        verbose_name_plural = "fotos"
        verbose_name = "foto"
        ordering = ("user",)

    def __str__(self):
        return self.file.name

    def save_db(self):
        from django.db import connection

        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO "core_photo" ("user_id", "file") VALUES (%s, %s) RETURNING id',
                [self.user.pk, self.file.name],
            )

            return cursor.fetchone()[0]

    def save(self):
        self.file.save(self.file.name, self.file.file, save=False)
        self.pk = self.save_db()


class Reference(models.Model):
    name = models.CharField("nome", max_length=255)
    title = models.CharField("título", max_length=255)
    date_access = models.DateTimeField("data do acesso")
    user = models.ForeignKey(
        "auth.User", verbose_name="usuário", on_delete=models.CASCADE, null=True, blank=True
    )

    objects_db = ReferenceDB

    class Meta:
        verbose_name_plural = "referências"
        verbose_name = "referência"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Comment(models.Model):
    article = models.ForeignKey("articles.Article", verbose_name="artigo", on_delete=models.CASCADE)
    content = models.TextField("conteúdo")
    user = models.ForeignKey("auth.User", verbose_name="usuário", on_delete=models.CASCADE)
    created_at = models.DateTimeField("criado em", auto_now_add=True)

    objects_db = CommentDB

    class Meta:
        verbose_name_plural = "comentários"
        verbose_name = "comentário"
        ordering = ("-created_at",)

    def __str__(self):
        return self.content

    def save_db(self):
        from django.db import connection

        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO "core_comment" ("article_id", "content", "user_id", "created_at") VALUES (%s, %s, %s, %s) RETURNING id',
                [
                    self.article.pk,
                    self.content,
                    self.user.pk,
                    self.created_at,
                ],
            )

            return cursor.fetchone()[0]

    def save(self):
        self.created_at = timezone.now()
        self.pk = self.save_db()

bioquery/articles/forms.py
from django import forms
from django.core.exceptions import ValidationError

from bioquery.core.models import Category, DNA, Photo, Reference, Comment

from .models import Article


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]


class ReferenceForm(forms.ModelForm):
    class Meta:
        model = Reference
        fields = ["name", "title", "date_access"]


class DNAForm(forms.ModelForm):
    class Meta:
        model = DNA
        fields = ["name", "sequence"]


class ArticleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        self.fields["category"].choices = tuple(
            [(category.pk, category.name) for category in Category.objects_db.all()]
        )
        self.fields["dnas"].choices = tuple(
            [(dna.pk, dna.name) for dna in DNA.objects_db.all(user_id=user.id)]
        )
        self.fields["photo"].choices = tuple(
            [(photo.pk, photo.file) for photo in Photo.objects_db.all(user_id=user.id)]
        )
        self.fields["references"].choices = tuple(
            [
                (reference.pk, reference.name)
                for reference in Reference.objects_db.all(user_id=user.id)
            ]
        )

    photo = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=(),
    )
    category = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
        choices=(),
    )
    dnas = forms.MultipleChoiceField(
        required=False,
        widget=forms.SelectMultiple(attrs={"class": "form-control"}),
        choices=(),
    )
    references = forms.MultipleChoiceField(
        required=False,
        widget=forms.SelectMultiple(attrs={"class": "form-control"}),
        choices=(),
    )

    class Meta:
        model = Article
        fields = ["title", "content"]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Digite o título"}
            ),
            "content": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Digite o conteúdo"}
            ),
        }

    def clean_title(self):
        title = self.cleaned_data["title"]
        words = [w.capitalize() for w in title.split()]
        return " ".join(words)

    def clean(self):
        self.cleaned_data = super().clean()

        if not self.cleaned_data.get("title"):
            raise ValidationError("Informe um título.")

        if not self.cleaned_data.get("content"):
            raise ValidationError("Informe o conteúdo.")

        return self.cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        if commit:
            instance.save_db()
        return instance


class PhotoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["file"].required = False

    class Meta:
        model = Photo
        fields = ["file"]

bioquery/articles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.shortcuts import redirect, render, resolve_url as r
from django.db import transaction
from bioquery.core.models import Category, Photo, Reference, DNA, Comment
from django.utils.text import slugify

from .forms import ArticleForm, PhotoForm, ReferenceForm, DNAForm, CommentForm
from .models import Article


@login_required
def delete_dna(request, id):
    DNA.objects_db.delete(id, request.user.id)
    return redirect(r("articles:dnas"))


@login_required
def edit_dna(request, id):
    dna = DNA.objects_db.get(id=id)
    if request.method == "POST":
        form = DNAForm(request.POST)

        if not form.is_valid():
            return render(
                request,
                "articles/dna_form.html",
                {"form": form},
            )

        DNA.objects_db.update(dna.id, form.cleaned_data["name"], form.cleaned_data["sequence"])
        return redirect(r("articles:dnas"))
    return render(
        request,
        "articles/dna_form.html",
        {
            "form": DNAForm(initial={"name": dna.name, "sequence": dna.sequence}),
        },
    )


@login_required
def edit_reference(request, id):
    reference = Reference.objects_db.get(id=id)
    if request.method == "POST":
        form = ReferenceForm(request.POST)

        if not form.is_valid():
            return render(
                request,
                "articles/reference_form.html",
                {"form": form},
            )

        Reference.objects_db.update(
            reference.id,
            form.cleaned_data["name"],
            form.cleaned_data["title"],
            form.cleaned_data["date_access"],
        )
        return redirect(r("articles:references"))
    return render(
        request,
        "articles/reference_form.html",
        {
            "form": ReferenceForm(
                initial={
                    "name": reference.name,
                    "title": reference.title,
                    "date_access": reference.date_access,
                }
            ),
        },
    )


@login_required
def dnas(request):
    dnas = DNA.objects_db.all(user_id=request.user.id)
    return render(
        request,
        "articles/dnas.html",
        {"dnas": dnas},
    )


@login_required
def new_dna(request):
    if request.method == "POST":
        form = DNAForm(request.POST)

        if not form.is_valid():
            return render(
                request,
                "articles/dna_form.html",
                {"form": form},
            )
        dnas = form.save(commit=False)
        dnas.user = request.user
        dnas.save()
        return redirect(r("articles:dnas"))
    return render(
        request,
        "articles/dna_form.html",
        {
            "form": DNAForm(),
        },
    )


@login_required
def references(request):
    references = Reference.objects_db.all(user_id=request.user.id)
    return render(
        request,
        "articles/references.html",
        {"references": references},
    )


@login_required
def new_reference(request):
    if request.method == "POST":
        form = ReferenceForm(request.POST)

        if not form.is_valid():
            return render(
                request,
                "articles/reference_form.html",
                {"form": form},
            )
        dna = form.save(commit=False)
        dna.user = request.user
        dna.save()
        return redirect(r("articles:references"))
    return render(
        request,
        "articles/reference_form.html",
        {
            "form": ReferenceForm(),
        },
    )


@login_required
def delete_reference(request, id):
    Reference.objects_db.delete(id, request.user.id)
    return redirect(r("articles:references"))


@login_required
def new(request):
    if request.method == "POST":
        return create(request)
    return empty_form(request)


@login_required
def update_article(request, slug):
    article = Article.objects_db.get_object_or_404(slug=slug)
    if request.method == "POST":
        return update(article.id, request)
    dnas = DNA.objects_db.all_from_article(article.id)
    references = Reference.objects_db.all_from_article(article.id)
    photo = Photo.objects_db.get_from_article(article.id)

    return empty_form(
        request,
        {
            "title": article.title,
            "content": article.content,
            "category": article.category_id,
            "photo": photo.id,
            "references": [reference.id for reference in references],
            "dnas": [dna.id for dna in dnas],
        },
    )


@login_required
def delete_article(request, slug):
    article = Article.objects_db.get_object_or_404(slug=slug)
    Article.objects_db.delete(article.id, request.user.id)
    return redirect(r("pannel"))


@login_required
def empty_form(request, data={}):
    return render(
        request,
        "articles/article_form.html",
        {
            "form": ArticleForm(initial=data, user=request.user),
            "photo_form": PhotoForm(),
        },
    )


def update(article_id, request):
    form = ArticleForm(request.POST, user=request.user)
    photo_form = PhotoForm(request.POST, request.FILES)

    if not form.is_valid() or not photo_form.is_valid():
        return render(
            request,
            "articles/article_form.html",
            {"form": form, "photo_form": photo_form},
        )

    with transaction.atomic():
        photo = None
        if photo_form["file"].data:
            photo = photo_form.save(commit=False)
            photo.user = request.user
            photo.save()
        elif form["photo"].data:
            photo = Photo.objects_db.get(id=form["photo"].data)

        Article.objects_db.update(
            article_id,
            form.cleaned_data["title"],
            slugify(form.cleaned_data["title"]),
            form.cleaned_data["content"],
            form.cleaned_data["category"],
        )

        if photo:
            Article.objects_db.update_photo(article_id, photo.id)

        Article.objects_db.set_dnas(article_id, form["dnas"].data)
        Article.objects_db.set_references(article_id, form["references"].data)

    return redirect(r("pannel"))


def create(request):
    form = ArticleForm(request.POST, user=request.user)
    photo_form = PhotoForm(request.POST, request.FILES)

    if not form.is_valid() or not photo_form.is_valid():
        return render(
            request,
            "articles/article_form.html",
            {"form": form, "photo_form": photo_form},
        )

    with transaction.atomic():
        photo = None
        if photo_form["file"].data:
            photo = photo_form.save(commit=False)
            photo.user = request.user
            photo.save()
        elif form["photo"].data:
            photo = Photo.objects_db.get(id=form["photo"].data)

        article = form.save(commit=False)
        article.category = Category.objects_db.get(pk=form["category"].data)
        article.user = request.user
        if photo:
            article.photo = photo
        article.save_db()

        Article.objects_db.set_dnas(article.pk, form["dnas"].data)
        Article.objects_db.set_references(article.pk, form["references"].data)
    return redirect(r("articles:detail", slug=article.slug))


def detail(request, slug):
    if request.method == "POST":
        return add_comment(request, slug)

    return view_article(request, slug)

def view_article(request, slug):
    article = Article.objects_db.get_complex_or_404(slug=slug)
    references = Reference.objects_db.from_article(article["id"])
    dnas = DNA.objects_db.from_article(article["id"])
    comments = Comment.objects_db.filter_by_article__pk(article["id"])
    return render(
        request,
        "articles/article_detail.html",
        {
            "article": article,
            "references": references,
            "dnas": dnas,
            "comments": comments,
            "comment_form": CommentForm()
        },
    )


@login_required
def add_comment(request, slug):
    article = Article.objects_db.get_complex_or_404(slug=slug)

    comment_form = CommentForm(request.POST)
    if not comment_form.is_valid():
        references = Reference.objects_db.from_article(article["id"])
        dnas = DNA.objects_db.from_article(article["id"])
        comments = Comment.objects_db.filter_by_article__pk(article["id"])

        return render(
            request,
            "articles/article_detail.html",
            {
                "article": article,
                "references": references,
                "dnas": dnas,
                "comments": comments,
                "comment_form": comment_form
            },
        )

    comment = comment_form.save(commit=False)
    comment.article = Article(id=article["id"])
    comment.user = request.user
    comment.save()
    messages.success(request, 'Comentário adicionado com sucesso.')
    return redirect(r("articles:detail", slug=article["slug"]))

bioquery/articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block title %}{{ article.title }} - BioQuery{% endblock title %}

{% block content %}
<div class="content-wrap py-160">
  <div class="container isotope">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Fechar">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    <div class="row justify-content-center">
      {% if article.photo %}
        <div class="col-12 text-center mb-60" style="transition-duration: 700ms; opacity: 1; transform: translateY(0px);">
          <img src="/media/{{ article.photo }}" width="300px" />
        </div>
      {% endif %}
      <div class="col-12 col-lg-10">
        <div class="row">
          <div class="col-12 mb-20">
            <p class="subtitle mt-n10" style="transform: translateY(0px); transition-duration: 500ms; opacity: 1; text-transform: lowercase;">{{ article.category.name }}</p>
            <h3 class="mb-n7" style="transform: translateY(0px); transition-duration: 500ms; opacity: 1;">{{ article.title }}</h3>
          </div>
          <div class="col-12" style="transition-duration: 700ms; opacity: 1; transform: translateY(0px);">
            <p class="mb-3">{{ article.content }}</p>
          </div>
          <div class="col-12" style="transition-duration: 700ms; opacity: 1; transform: translateY(0px);">
            <h3 class="mt-60">Referências</h3>
            {% for ref in references %}
              <div class="mb-30">
                <p class="m-0">{{ ref.name }}</p>
                <p class="m-0">{{ ref.title }}</p>
                <p class="m-0">{{ ref.date_access }}</p>
              </div>
            {% endfor %}
          </div>
          <div class="col-12" style="transition-duration: 700ms; opacity: 1; transform: translateY(0px);">
            <h3>DNA's</h3>
            {% for dna in dnas %}
            <div class="mb-30">
              <p class="m-0">{{ dna.name }}</p>
              <p class="m-0">{{ dna.sequence }}</p>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="row justify-content-center gh-1 mt-60 mb-100">
        <div class="col-12 col-lg-6 text-center">
          <svg
            class="mb-30"
            width="38"
            height="24"
            viewBox="0 0 38 24"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M0 24L10.1466 0H18.801L13.4293 24H0ZM19.199 24L29.3455 0H38L32.5288 24H19.199Z"
              fill="currentColor"
            ></path>
          </svg>
          <blockquote class="mt-6 mb-60">Deixe um comentário.</blockquote>
        </div>
        {% if user.is_authenticated %}
        <div
          class="col-12 col-lg-8"
          style="transform: translateY(0px); transition-duration: 400ms; opacity: 1"
        >
          <form method="POST" action=".">
            {% csrf_token %}
            <textarea
              name="content"
              class="form-control"
              rows="1"
              placeholder="Escreva um comentário..."
            ></textarea>
            <button
              type="submit"
              class="btn btn-dark btn-with-ball mt-20"
            >
              enviar<span class="btn-ball" style="transform: translateY(0px)"></span>
            </button>
          </form>
        </div>
        {% else %}
        <div class="col-12 col-lg-8 text-center">
          <a class="btn btn-dark btn-with-ball" href="{% url 'account_login' %}?next={{ request.path }}">
            Faça login para adicionar um comentário!
          </a>
        </div>
        {% endif %}
        <div class="col-12 col-lg-8 text-center">
          <div class="accordion mt-40 pt-5" id="accordionAbout">
            {% for comment in comments %}
            <div class="accordion-item">
              <div class="d-flex justify-content-between h5">
                <span>🔥 {{ comment.user }}</span>
                <span><small class="text-muted" style="font-size: 60%;">{{ comment.created_at }}</small></span>
              </div>
              <div
                id="collapseDesign"
                class="collapse show"
                data-parent="#accordionAbout"
              >
                <div class="collapse-content px-0">
                  <p class="mb-0 text-left font-size-16">
                    {{ comment.content }}
                  </p>
                </div>
              </div>
            </div>
            {% empty %}
            <div class="accordion-item">
              <div
                id="collapseDesign"
                class="collapse show"
                data-parent="#accordionAbout"
              >
                <div class="collapse-content px-0">
                  <p class="mb-0 font-size-16 text-secondary">
                    Ainda não há comentários...
                  </p>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

bioquery/articles/templates/articles/article_form.html
{% extends 'base.html' %}

{% block title %}Novo artigo - BioQuery{% endblock title %}

{% block content %}
<div class="content-wrap py-160">
  <div class="container isotope">
    <h1 class="h2 mb-0">Formulário do Artigo</h1>
    <div class="text-right mb-60">
        <a href="/articles/references" class="btn-primary rounded-sm p-9">Referências</a>
        <a href="/articles/dnas" class="btn-primary rounded-sm p-9">DNA's</a>
    </div>
    <form method="POST" action="." enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="row gh-1 gv-2">
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.title.errors }}
          {{ form.title }}
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.content.errors }}
          {{ form.content.label_tag }}
          {{ form.content }}
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.category.errors }}
          {{ form.category.label_tag }}
          {{ form.category }}
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.dnas.errors }}
          {{ form.dnas.label_tag }}
          {{ form.dnas }}
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.references.errors }}
          {{ form.references.label_tag }}
          {{ form.references }}
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.photo.errors }}
          {{ form.photo.label_tag }}
          {{ form.photo }}
        </div>
        <hr class="mt-30 width-70px" />
        <div class="col-12">
          <h2 class="h4">Adicione uma imagem <span style="font-size: 1rem; color: #cecece; font-style: italic;">- Opcional</span></h2>
          {{ photo_form.non_field_errors }}
          <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
            {{ photo_form.file.errors }}
            {{ photo_form.file }}
          </div>
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          <button class="btn btn-dark btn-with-ball mt-20" type="submit" name="button">enviar!<span class="btn-ball"></span></button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

bioquery/articles/templates/articles/dna_form.html
{% extends 'base.html' %}

{% block title %}Novo artigo - BioQuery{% endblock title %}

{% block content %}
<div class="content-wrap py-160">
  <div class="container isotope">
    <h1 class="h2 mb-0">Dados do DNA</h1>
    <form method="POST" action="." enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="row gh-1 gv-2">
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.name.errors }}
          {{ form.name.label_tag }}
          {{ form.name }}
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.sequence.errors }}
          {{ form.sequence.label_tag }}
          {{ form.sequence }}
        </div>

        <hr class="mt-30 width-70px" />
   
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          <button class="btn btn-dark btn-with-ball mt-20" type="submit" name="button">enviar!<span class="btn-ball"></span></button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

bioquery/articles/templates/articles/dnas.html
{% extends 'base.html' %}

{% block title %}Novo artigo - BioQuery{% endblock title %}

{% block content %}
<div class="container " style="min-height: calc(100vh - 94px)">
    <div class="row mt-60">
        <h2>DNA's</h2>
        <div class="ml-auto">
            <a class="btn-primary rounded-sm p-10" href="new">Adicionar</a>
        </div>
    </div>
    {% for dna in dnas %}
    <div class="row">
      <div class="col-12 col-md-10 mt-3">
          <div class="card">
              <div class="card-horizontal">
                  <div class="card-body">
                      <h4 class="card-title">{{dna.name}}</h4>
                      <p class="card-text">{{dna.sequence}}</p>
                  </div>
              </div>
              <div class="card-footer">
                  <small class="text-muted">{{ref.date_access}}</small>
              </div>
          </div>
      </div>
      <div class="col-12 col-md-2">
        <a href="/articles/dnas/{{dna.id}}/edit/">Editar</a>
        <a href="/articles/dnas/{{dna.id}}/delete/">Remover</a>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock content %}

bioquery/articles/templates/articles/reference_form.html
{% extends 'base.html' %}

{% block title %}Novo artigo - BioQuery{% endblock title %}

{% block content %}
<div class="content-wrap py-160">
  <div class="container isotope">
    <h1 class="h2 mb-0">Dados de referência</h1>
    <form method="POST" action="." enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="row gh-1 gv-2">
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.name.errors }}
          {{ form.name.label_tag }}
          {{ form.name }}
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.title.errors }}
          {{ form.title.label_tag }}
          {{ form.title }}
        </div>
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          {{ form.date_access.errors }}
          {{ form.date_access.label_tag }}
          {{ form.date_access }}
        </div>

        <hr class="mt-30 width-70px" />
   
        <div class="col-12" style="transform: translateY(0px); transition-duration: 400ms; opacity: 1;">
          <button class="btn btn-dark btn-with-ball mt-20" type="submit" name="button">enviar!<span class="btn-ball"></span></button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
        $('#id_date_access').datetimepicker({
            format:'d/m/Y h:m'
        });
    })
</script>
{% endblock %}

bioquery/articles/templates/articles/references.html
{% extends 'base.html' %}

{% block title %}Novo artigo - BioQuery{% endblock title %}

{% block content %}
<div class="container " style="min-height: calc(100vh - 94px)">
    <div class="row mt-60">
        <h2>Referências</h2>
        <div class="ml-auto">
            <a class="btn-primary rounded-sm p-10" href="new">Adicionar</a>
        </div>
    </div>
    {% for ref in references %}
    <div class="row">
      <div class="col-12 mt-3">
          <div class="card">
              <div class="card-horizontal">
                  <div class="card-body">
                      <h4 class="card-title">{{ref.title}}</h4>
                      <p class="card-text">{{ref.name}}</p>
                  </div>
                  <div class="mr-auto">
                    <a href="/articles/references/{{ref.id}}/edit/">Editar</a>
                    <a href="/articles/references/{{ref.id}}/delete/">Remover</a>
                  </div>
              </div>
              <div class="card-footer">
                  <small class="text-muted">{{ref.date_access}}</small>
              </div>
          </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock content %}