bioquery/articles/urls.py
from django.urls import path

from .views import (
    new,
    detail,
    references,
    new_reference,
    delete_reference,
    dnas,
    new_dna,
    edit_dna,
    delete_dna,
    delete_article,
    update_article,
    edit_reference,
)


app_name = "articles"

urlpatterns = [
    path("", new, name="new"),
    path("dnas/", dnas, name="dnas"),
    path("dnas/new/", new_dna, name="new_dna"),
    path("dnas/<int:id>/edit/", edit_dna, name="edit_dna"),
    path("references/", references, name="references"),
    path("references/new/", new_reference, name="new_reference"),
    path("references/<int:id>/delete/", delete_reference, name="delete_reference"),
    path("references/<int:id>/edit/", edit_reference, name="edit_reference"),
    path("dnas/<int:id>/delete/", delete_dna, name="delete_dnas"),
    path("<str:slug>/", detail, name="detail"),
    path("<str:slug>/delete/", delete_article, name="delete_article"),
    path("<str:slug>/edit/", update_article, name="edit_article"),
]

bioquery/core/urls.py
from django.urls import path

from .views import home, pannel, search


urlpatterns = [
    path("", home, name="home"),
    path("painel/", pannel, name="pannel"),
    path("search/", search, name="search"),
]

bioquery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


admin.site.enable_nav_sidebar = False

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("bioquery.articles.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("bioquery.core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bioquery/core/models.py
from django.db import models
from django.utils import timezone

from .managers import CategoryDB, DNADB, PhotoDB, ReferenceDB, CommentDB


class Category(models.Model):
    name = models.CharField("nome", max_length=255)
    description = models.TextField("descrição")

    objects_db = CategoryDB

    class Meta:
        verbose_name_plural = "categorias"
        verbose_name = "categoria"
        ordering = ("name",)

    def __str__(self):
        return self.name


class DNA(models.Model):
    name = models.CharField("nome", max_length=255)
    sequence = models.TextField("sequência")
    user = models.ForeignKey("auth.User", verbose_name="usuário", on_delete=models.CASCADE)

    objects_db = DNADB

    class Meta:
        verbose_name_plural = "DNA's"
        verbose_name = "DNA"
        ordering = ("-name",)

    def __str__(self):
        return self.name


class Photo(models.Model):
    user = models.ForeignKey("auth.User", verbose_name="usuário", on_delete=models.CASCADE)
    file = models.FileField("arquivo")

    objects_db = PhotoDB

    class Meta:
        verbose_name_plural = "fotos"
        verbose_name = "foto"
        ordering = ("user",)

    def __str__(self):
        return self.file.name

    def save_db(self):
        from django.db import connection

        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO "core_photo" ("user_id", "file") VALUES (%s, %s) RETURNING id',
                [self.user.pk, self.file.name],
            )

            return cursor.fetchone()[0]

    def save(self):
        self.file.save(self.file.name, self.file.file, save=False)
        self.pk = self.save_db()


class Reference(models.Model):
    name = models.CharField("nome", max_length=255)
    title = models.CharField("título", max_length=255)
    date_access = models.DateTimeField("data do acesso")
    user = models.ForeignKey(
        "auth.User", verbose_name="usuário", on_delete=models.CASCADE, null=True, blank=True
    )

    objects_db = ReferenceDB

    class Meta:
        verbose_name_plural = "referências"
        verbose_name = "referência"
        ordering = ("name",)

    def __str__(self):
        return self.name


class Comment(models.Model):
    article = models.ForeignKey("articles.Article", verbose_name="artigo", on_delete=models.CASCADE)
    content = models.TextField("conteúdo")
    user = models.ForeignKey("auth.User", verbose_name="usuário", on_delete=models.CASCADE)
    created_at = models.DateTimeField("criado em", auto_now_add=True)

    objects_db = CommentDB

    class Meta:
        verbose_name_plural = "comentários"
        verbose_name = "comentário"
        ordering = ("-created_at",)

    def __str__(self):
        return self.content

    def save_db(self):
        from django.db import connection

        with connection.cursor() as cursor:
            cursor.execute(
                'INSERT INTO "core_comment" ("article_id", "content", "user_id", "created_at") VALUES (%s, %s, %s, %s) RETURNING id',
                [
                    self.article.pk,
                    self.content,
                    self.user.pk,
                    self.created_at,
                ],
            )

            return cursor.fetchone()[0]

    def save(self):
        self.created_at = timezone.now()
        self.pk = self.save_db()

bioquery/core/views.py
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from bioquery.articles.models import Article


@login_required
def pannel(request):
    articles = Article.objects_db.filter_all(user_id=request.user.id)
    return render(request, "pannel.html", {"articles": articles})


def search(request):
    query = request.GET.get("q", "")
    articles = Article.objects_db.filter_by_title_and_content(query)
    return render(request, "search.html", {"query": query, "articles": articles})


def home(request):
    return render(request, "index.html")

bioquery/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>{% block title %}BioQuery - Aprenda mais lendo artigos!{% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&amp;display=swap"
    />
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/global.css' %}" />
    <link rel="stylesheet" href="{% static 'css/feather.css' %}" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
  </head>
  <body class="navbar-scroll navbar-show">

    {% block nav %} {% include "nav.html" %} {% endblock nav %}

    {% block content %} {% endblock content %}

    {% block scripts %} {% endblock scripts %}

    <footer class="w-100 pt-40 pb-40" style="background: #525b68">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-12">
            <a class="text-white h4" href="">BioQuery</a>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"></script>
  </body>
</html>

bioquery/core/templates/index.html
{% extends 'base.html' %} {% load static %}
{% block nav %} {% endblock %}
{% block content %}
<style>
  .landing {
    position: relative;
    width: 100%;
    height: 100%;
    background-image: url(/static/img/initial_background.svg);
    background-repeat: no-repeat;
    background-size: cover;
    display: block;
  }
  .landing h2 {
    font-family: "Roboto Condensed";
    font-weight: bold;
    color: #2b2b2b;
  }
</style>
<section class="landing min-vh-100">
  <div class="container">
      {% include "nav.html" %}
    <div class="row mt-60">
      <div class="col-12 col-md-6 pt-60">
        <h2 class="h3">Search for even the smallest molecules.</h2>
        <hr class="m-0" style="width: 40px; color: #f56c1f; border-width: 3px" />
        <form method="GET" action="search">
        <div class="input-group mb-3 mt-40">
          <input name="q" class="form-control p-2" style="border: 1px solid #f56c1f;" />
          <button type="submit" class="input-group-append p-0 m-0" style="border: 1px solid #F56C1F;">
            <i style="line-height: 2rem; background-color: #F56C1F; padding: 5px 20px" class="feather-search text-white"></i>
          </button>
        </div>
      </form>
      </div>
      <div class="col-md-6 text-center d-none d-sm-block">
        <img style="width: 264px" src="{% static 'img/biological.svg' %}" />
      </div>
    </div>
  </div>
</section>
<section class="mt-60 mb-60 w-100">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 text-center">
        <h2 class="h3">Lots of data</h2>
        <p style="font-size: 20px">
          We provide a quick way to search for gene expressions, Phenotypes, Proteins and more
          amazing things.
        </p>
        <a class="button" href="#">View more</a>
      </div>
    </div>
  </div>
</section>
<section class="mt-60 mb-60 w-100">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-3 text-center">
        <img class="img-fluid" src="{% static 'img/people_on_the_grass.svg' %}" />
      </div>
      <div class="col-12 col-md-9 pl-30">
        <h3>The union makes the difference</h3>
        <p style="font-size: 18px">
          You can contribute and help many people who seek your knowledge. Edit the pages,
          participate in the forum and make it possible to create amazing things.
        </p>
        <a>PARTICIPATE</a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

bioquery/core/templates/nav.html
<header class="navbar navbar-top navbar-expand-lg position-relative">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}"> BioQuery </a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a href="{% url 'search' %}" class="nav-link">
          <span class="nav-link-name">Pesquisar</span>
        </a>
        {% if user.is_authenticated %}
        <a href="{% url 'pannel' %}" class="nav-link">
          <span class="nav-link-name">Painel</span>
        </a>
        <a href="{% url 'articles:new' %}" class="nav-link">
          <span class="nav-link-name">Adicionar artigo</span>
        </a>
        <a href="{% url 'account_logout' %}" class="nav-link">
          <span class="nav-link-name">Sair</span>
        </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="nav-link">
          <span class="nav-link-name">Acesso</span>
        </a>
        {% endif %}
      </li>
    </ul>
  </div>
</header>

bioquery/core/templates/pannel.html
{% extends "base.html" %} {% block content %}
<div class="container-fluid" style="min-height: calc(100vh - 94px)">
  <div class="row justify-content-center pt-60 pb-60">
    <div class="col-10 d-flex">
      <div>
        <h4>Suas publicações</h4>
        <p>Resultados encontrados</p>
      </div>
      <div class="ml-auto">
        <a class="btn-primary py-10 px-30 rounded-sm" href="{% url 'articles:references' %}">Referências</a>
        <a class="btn-primary py-10 px-30 rounded-sm" href="{% url 'articles:dnas' %}">DNA's</a>
      </div>
    </div>
    <div class="col-md-10">
      {% if articles|length == 0 %}
      <p class="alert-info p-2 text-center">Nenhum resultado encontrado</p>
      {% endif %}
      
      {% for article in articles %}
        <div class="row mb-20">
          <div class="col-12 col-md-2">
            <img class="img-fluid" src="/media/{{article.photo}}" alt="image" />
          </div>
          <div class="col-md-8 mt-3">
            <div class="card">
              <div class="card-horizontal">
                <div class="card-body">
                  <h4 class="card-title">{{article.title}}</h4>
                  <p class="card-text">{{article.content|truncatechars:300}}</p>
                </div>
              </div>
              <div class="card-footer">
                <small class="text-muted">Categoria: {{article.category}}</small><br />
                <small class="text-muted">Autor: {{article.author}}</small><br />
                <small class="text-muted">{{article.date}}</small>
              </div>
            </div>
          </div>
          <div class="col-md-2">
            <a href="/articles/{{article.slug}}/edit/">Editar</a>
            <a href="/articles/{{article.slug}}/delete/">Remover</a>
            <a href="/articles/{{article.slug}}/">Visualizar</a>
          </div>
        </div>
      
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}

bioquery/core/templates/search.html
{% extends "base.html" %} {% block content %}
<div class="container-fluid" style="min-height: calc(100vh - 94px)">
  <div class="row justify-content-center pt-60 pb-60 bg-orange mb-20">
    <div class="col-md-8">
      <form>
        <h3>Pesquisar</h3>
        <input
          name="q"
          placeholder="Pesquise aqui..."
          class="form-control bg-white rounded-sm p-4"
        />
      </form>
    </div>
  </div>
  {% if articles|length == 0 %}
  <div class="alert-info p-20">Nenhum resultado encontrado.</div>
  {% endif %}
  {% for article in articles %}
  <a class="w-100" href="/articles/{{article.slug}}">
    <div class="row mb-20">
      <div class="col-12 col-md-3">
        <img class="img-fluid" src="/media/{{article.photo}}" alt="image" />
      </div>
      <div class="col-md-9 mt-3">
        <div class="card">
          <div class="card-horizontal">
            <div class="card-body">
              <h4 class="card-title">{{article.title}}</h4>
              <p class="card-text">{{article.content|truncatechars:300}}</p>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-muted">Categoria: {{article.category}}</small></br>
            <small class="text-muted">Autor: {{article.author}}</small></br>
            <small class="text-muted">{{article.date}}</small>
          </div>
        </div>
      </div>
    </div>
  </a>
  {% endfor %}
</div>
{% endblock content %}